; Echo GPPC SAPI5 -- Inno Setup installer.
;
; Hand-written rather than generated by CPack and patched afterwards. The
; generated route in this repository's previous engine needed a regex
; post-processing step to inject its [Code] section, and it registered each
; engine with the wrong bitness of regsvr32 -- {sys} is System32, which is the
; 64-bit one, and {syswow64} is the 32-bit one, so the two were swapped.
; Registration here is done with Inno's own regserver flag, which picks the
; right view for each file and undoes itself on uninstall.
;
; Build with:  ISCC.exe installer\echogppc.iss
; (expects build_all.bat to have staged output\ first)

#define AppName        "Echo GPPC SAPI5"
#define AppVersion     "1.0.0"
#define AppPublisher   "Echo GPPC SAPI5 project"
#define ConfigExe      "EchoGPPCConfig.exe"
#define Stage          "..\output"

[Setup]
AppId={{7C4F1B2E-9A63-4D8F-B5E1-2F6A0C3D8E47}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
VersionInfoVersion={#AppVersion}
DefaultDirName={autopf}\Echo GPPC SAPI5
DefaultGroupName=Echo GPPC SAPI5
UninstallDisplayIcon={app}\{#ConfigExe}
UninstallDisplayName={#AppName}
OutputDir={#Stage}
OutputBaseFilename=EchoGPPC_SAPI5_Setup
SetupIconFile=echogppc.ico
Compression=lzma2/max
SolidCompression=yes

; Registering a SAPI voice enumerator means writing to HKLM, which SAPI reads
; from and nowhere else -- so this genuinely cannot run unelevated.
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible

; A full log of everything setup did, which is the whole point of asking for
; detailed logs: it is copied somewhere findable at the end of the run.
SetupLogging=yes

; Screen reader notes. The stock wizard is built from standard Win32 controls
; and is read correctly as it stands; what matters is not undermining that:
;
;  * No custom-drawn or owner-drawn pages, and no images carrying information.
;  * WizardStyle=classic keeps the plain, long-established layout rather than
;    the modern one's larger decorative header, which adds nothing that is
;    announced and pushes the real content further down the tab order.
;  * Every page below has explanatory text, so a page is never just a title
;    and a Next button.
;  * The licence page is kept, so the third-party terms cannot be skipped past
;    without being presented.
WizardStyle=classic
DisableWelcomePage=no
DisableDirPage=no
DisableProgramGroupPage=no
DisableReadyPage=no
ShowLanguageDialog=no
AllowCancelDuringInstall=yes

; NEVER close applications automatically. The most likely host for this engine
; is a screen reader, and shutting it down mid-install would leave a blind user
; with no speech and a modal dialog they cannot read. Files that are in use are
; scheduled for replacement on the next restart instead.
CloseApplications=no
RestartIfNeededByRun=no

LicenseFile={#Stage}\THIRD_PARTY_LICENSES.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
; No "&" accelerator in this description. Inno's tasks list is a custom
; check-list control that hands MSAA the raw caption, ampersand and all, so a
; screen reader reads the accelerator marker out loud -- unlike a standard
; checkbox, where Windows strips it. Items here are reached with the arrow
; keys and toggled with Space, so the accelerator was buying nothing anyway.
Name: "desktopicon"; Description: "Create a desktop shortcut to the Echo GPPC configuration utility"; GroupDescription: "Shortcuts:"

[Files]
; --- shared by both architectures -----------------------------------------
; The Textalker ROM pairs and both emulator DLLs live in the install root.
; Every module looks beside itself and then one directory up, so the 32-bit
; engine in x86\ finds all of this without a second copy of any of it.
Source: "{#Stage}\textalker.ram.bin";        DestDir: "{app}"; Flags: ignoreversion
Source: "{#Stage}\textalker.obj.bin";        DestDir: "{app}"; Flags: ignoreversion
Source: "{#Stage}\textalker_v13.ram.bin";    DestDir: "{app}"; Flags: ignoreversion
Source: "{#Stage}\textalker_v13.obj.bin";    DestDir: "{app}"; Flags: ignoreversion
Source: "{#Stage}\echotalk32.dll";           DestDir: "{app}"; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#Stage}\THIRD_PARTY_LICENSES.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Stage}\readme.html";              DestDir: "{app}"; Flags: ignoreversion

; --- 32-bit engine, installed on every machine -----------------------------
; The 32bit flag is spelled out rather than left to default. In 64-bit install
; mode Inno treats entries as 64-bit unless told otherwise, and its log says
; "Registering 64-bit DLL/OCX" for this file without it -- which is at best
; confusing in a support log, since a 64-bit process cannot load this DLL at
; all. Being explicit puts the registration in the 32-bit registry view, where
; 32-bit SAPI applications look for it, and makes the log say so.
Source: "{#Stage}\x86\EchoGPPCSAPI.dll"; DestDir: "{app}\x86"; \
    Flags: ignoreversion regserver 32bit restartreplace uninsrestartdelete
Source: "{#Stage}\x86\EchoGPPCTest.exe"; DestDir: "{app}\x86"; Flags: ignoreversion

; --- 64-bit engine and tools, on 64-bit Windows only -----------------------
Source: "{#Stage}\echotalk64.dll"; DestDir: "{app}"; \
    Check: Is64BitInstallMode; Flags: ignoreversion restartreplace uninsrestartdelete
Source: "{#Stage}\EchoGPPCSAPI.dll"; DestDir: "{app}"; \
    Check: Is64BitInstallMode; \
    Flags: ignoreversion regserver 64bit restartreplace uninsrestartdelete
Source: "{#Stage}\EchoGPPCTest.exe"; DestDir: "{app}"; \
    Check: Is64BitInstallMode; Flags: ignoreversion

; --- configuration utility, matched to the machine -------------------------
Source: "{#Stage}\{#ConfigExe}";     DestDir: "{app}"; \
    Check: Is64BitInstallMode; Flags: ignoreversion
Source: "{#Stage}\x86\{#ConfigExe}"; DestDir: "{app}"; \
    Check: not Is64BitInstallMode; Flags: ignoreversion

[Icons]
Name: "{group}\Echo GPPC Configuration"; Filename: "{app}\{#ConfigExe}"; \
    Comment: "Adjust the voice, rate, pitch and other settings of the Echo GPPC speech engine"
Name: "{group}\Echo GPPC read me"; Filename: "{app}\readme.html"; \
    Comment: "About the emulated Echo II and what each setting does"
Name: "{group}\Uninstall Echo GPPC SAPI5"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Echo GPPC Configuration"; Filename: "{app}\{#ConfigExe}"; \
    Tasks: desktopicon; \
    Comment: "Adjust the voice, rate, pitch and other settings of the Echo GPPC speech engine"

[Run]
Filename: "{app}\{#ConfigExe}"; \
    Description: "Open the Echo GPPC &configuration utility"; \
    Flags: postinstall nowait skipifsilent

[UninstallDelete]
; Anything the engine created next to itself at run time.
Type: filesandordirs; Name: "{app}\x86"
Type: dirifempty; Name: "{app}"

[Code]

const
  TokenEnumsKey = 'Software\Microsoft\Speech\Voices\TokenEnums\EchoGPPC';

var
  RegistrationWarning: String;

// Copies setup's own log somewhere a person can actually find it, next to the
// engine's logs, so a bug report can carry both without hunting through TEMP.
procedure SaveSetupLog();
var
  Target: String;
begin
  Target := ExpandConstant('{localappdata}\EchoGPPC\logs');
  if not ForceDirectories(Target) then
  begin
    Log('Could not create ' + Target + '; the setup log stays in TEMP.');
    Exit;
  end;
  Target := Target + '\install-' + GetDateTimeString('yyyymmdd-hhnnss', '-', '-') + '.log';
  // The log is still open, so it is copied rather than moved.
  if CopyFile(ExpandConstant('{log}'), Target, False) then
    Log('Setup log copied to ' + Target)
  else
    Log('Could not copy the setup log to ' + Target);
end;

procedure LogEnvironment();
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  // Built by concatenation rather than Format(): Inno's parser treats any
  // line whose first non-blank character is '[' as a section tag, even inside
  // [Code], so an argument array cannot start a line.
  Log('Echo GPPC SAPI5 ' + ExpandConstant('{#AppVersion}') +
      ' installing on Windows ' + IntToStr(Version.Major) + '.' +
      IntToStr(Version.Minor) + ' build ' + IntToStr(Version.Build));
  if Is64BitInstallMode then
    Log('64-bit Windows: installing both the 64-bit and 32-bit engines.')
  else
    Log('32-bit Windows: installing the 32-bit engine only.');
  Log('Install directory: ' + ExpandConstant('{app}'));
end;

// Confirms the voices are really registered rather than trusting that
// DllRegisterServer returned success. SAPI reads enumerators only from HKLM,
// and in the 64-bit case each engine registers into its own registry view, so
// both views are checked.
procedure VerifyRegistration();
var
  Value: String;
  Ok32, Ok64: Boolean;
begin
  RegistrationWarning := '';

  Ok32 := RegQueryStringValue(HKLM32, TokenEnumsKey, 'CLSID', Value);
  if Ok32 then
    Log('32-bit voices registered, CLSID ' + Value)
  else
    Log('WARNING: the 32-bit voice enumerator is not present in the registry.');

  Ok64 := True;
  if Is64BitInstallMode then
  begin
    Ok64 := RegQueryStringValue(HKLM64, TokenEnumsKey, 'CLSID', Value);
    if Ok64 then
      Log('64-bit voices registered, CLSID ' + Value)
    else
      Log('WARNING: the 64-bit voice enumerator is not present in the registry.');
  end;

  if not (Ok32 and Ok64) then
    RegistrationWarning :=
      'Setup finished, but the Echo GPPC voices could not be registered with ' +
      'Windows Speech.' + #13#10 + #13#10 +
      'The files are installed correctly. Registering them again from an ' +
      'administrator command prompt usually fixes this:' + #13#10 + #13#10 +
      '    regsvr32 "' + ExpandConstant('{app}') + '\x86\EchoGPPCSAPI.dll"' + #13#10 +
      '    regsvr32 "' + ExpandConstant('{app}') + '\EchoGPPCSAPI.dll"' + #13#10 + #13#10 +
      'The full setup log has been saved in your EchoGPPC logs folder.';
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  case CurStep of
    ssInstall:
      LogEnvironment();
    ssPostInstall:
      begin
        VerifyRegistration();
        SaveSetupLog();
        if RegistrationWarning <> '' then
          MsgBox(RegistrationWarning, mbError, MB_OK);
      end;
  end;
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
end;

// The engine may be loaded into a running screen reader. Warn, and let the
// person decide when to restart it -- never close it for them.
function InitializeUninstall(): Boolean;
begin
  Result := True;
  Log('Uninstalling Echo GPPC SAPI5.');
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    // Deliberately left in place: %APPDATA%\EchoGPPC\settings.ini holds the
    // voice settings, and someone reinstalling almost always wants them back.
    Log('Voice settings in %APPDATA%\EchoGPPC were left in place.');
  end;
end;
